### ISSUE TITLE
ReferenceError: HTMLElement is not defined

### ISSUE THREAD

**Issue by ootes** [codedazur/toolkit#203]
When using this code with SSR (Nextjs) i get the following error in my Pipelines:

```
@apps/next:build: ReferenceError: HTMLElement is not defined
@apps/next:build:     at resolveMaybeRef (/opt/atlassian/pipelines/agent/build/apps/next/.next/server/chunks/861.js:652:213062)
@apps/next:build:     at MediaProvider (/opt/atlassian/pipelines/agent/build/apps/next/.next/server/chunks/861.js:652:216675)
```

https://github.com/codedazur/toolkit/blob/8bae49d37f9f209086487d7854ca8cb2192fc3ed/packages/react-essentials/utilities/resolveMaybeRef.ts#L6

**Comment by thijsdaniels** [comment]
Hmmmm good point 🤔 I'll need have a think about this...
